name: test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: check if python3 exist
        run: |
          echo ::set-output name=python::$(python3  --version  | cut -d " " -f 1 || true)
        id: python-version
      - name: setup python
        if: steps.python-version.outputs.python != 'Python'
        uses: actions/setup-python@v2
      - name: install dependency 
        run: |
          echo ${{ steps.python-version.outputs.python }}
          cd function
          python3 -m pip install --upgrade pip
          if [ -f requirements.txt ];then pip3 install -r requirements.txt -t .;fi
      - name: create zip bundle
        run: |
          cd ..
          zip -r ${{ github.sha }}.zip . -x '*.git*'
          pwd
      - name: archive zip
        uses: actions/upload-artifact@v2
        with:
          name: zipped-bundle
          path: build
          if-no-files-found: error
       
