name: test
on:
  push:
    branches:
      - main
jobs:
  init:
    runs-on: self-hosted
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with: 
          python-version: 3.8
      - name: install dependency 
        run: |
          cd function
          python -m pip install --upgrade pip
          if [ -f requirements.txt ];then pip install requirements -t .;fi
      - name: create zip bundle
        run: |
          zip -r ../${{ github.sha }}.zip .
      - name: archive zip
        uses: actions/upload-artifact@v2
        with:
          name: zipped-bundle
          path: ${{ github.sha }}.zip
       
